#!/usr/bin/env python3
"""
seed_lookup_tables.py
────────────────────
Ensures design-time lookup tables have the additional rows introduced after the
original July-2025 data-set.  Only idempotent INSERTs are emitted so the script
can be re-run safely.

Current scope: Designations only – we make sure the following extra names exist:
    • Senior HR Executive
    • HR Executive
    • IT Support Specialist
    • Senior IT Support Specialist
    • IT Systems Administrator

This script **does not** touch Roles, since those rows already exist in ddl.sql.
"""
from __future__ import annotations
import textwrap
from pathlib import Path

EXTRA_DESIGNATIONS = [
    "Senior HR Executive",
    "HR Executive",
    "IT Support Specialist",
    "Senior IT Support Specialist",
    "IT Systems Administrator",
]

_SQL_FILE = Path("csv_out/03_seed_designations.sql")


def run() -> None:
    _SQL_FILE.parent.mkdir(exist_ok=True)
    if _SQL_FILE.exists():
        _SQL_FILE.unlink()  # regen each run for idempotency

    with _SQL_FILE.open("w", encoding="utf-8") as fh:
        fh.write("-- Auto-generated by seed_lookup_tables.py – add only missing designations\n")
        for name in EXTRA_DESIGNATIONS:
            stmt = textwrap.dedent(f"""
            IF NOT EXISTS (SELECT 1 FROM dbo.Designations WHERE DesignationName = N'{name}')
                INSERT INTO dbo.Designations (DesignationName) VALUES (N'{name}');
            """)
            fh.write(stmt.strip() + "\n")

    print(f"✅  lookup tables seed script written → {_SQL_FILE}")


if __name__ == "__main__":
    run()
